version: '3'
services:
  quickstart-mysql:
    container_name: quickstart-mysql-source
    hostname: quickstart-mysql-source
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: confluent
      MYSQL_USER: confluent
      MYSQL_PASSWORD: confluent
      MYSQL_DATABASE: connect_test
    volumes:
      - ./mysql/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql

    ports:
      - "3307:3306"
    
    #command: "bash -c 'mysql -uconfluent -pconfluent < /tmp/db_setup.sql'"